// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import AccessCheckboxController from "./access_checkbox_controller.js"
application.register("access-checkbox", AccessCheckboxController)

import FilterController from "./filter_controller.js"
application.register("filter", FilterController)

import NavigationController from "./navigation_controller.js"
application.register("navigation", NavigationController)

import TabStateController from "./tab_state_controller.js"
application.register("tab-state", TabStateController)

import TextController from "./text_controller.js"
application.register("text", TextController)
