Layout/LineLength:
  AutoCorrect: false
  Max: 120
Layout/HashAlignment:
  EnforcedHashRocketStyle: table
  EnforcedColonStyle: table

Style/StringLiterals:
  Enabled: true
  EnforcedStyle: single_quotes
Style/Documentation:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'
    - 'config/**/*'
Metrics/ClassLength:
  CountAsOne: ['array', 'hash', 'heredoc']
Metrics/MethodLength:
  CountAsOne: ['array', 'hash', 'heredoc']
  Max: 14
Metrics/ModuleLength:
  CountAsOne: ['array', 'hash', 'heredoc']

AllCops:
  Exclude:
    - '.git/**/*'
    - '.github/**/*'
    - 'db/**/*'
    - 'config/**/*'
    - 'script/**/*'
    - 'bin/**/*'
    - 'lib/**/*'
    - 'log/**/*'
    - 'tmp/**/*'
    - 'node_modules/**/*'
    - 'vendor/**/*'
