Metrics/LineLength:
  Max: 120
Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'
AllCops:
  Exclude:
    - 'db/**/*'
    - 'config/**/*'
    - 'script/**/*'
    - 'bin/**/*'
    - 'lib/**/*'
    - 'node_modules/**/*'
    - 'vendor/**/*'
    - '.git/**/*'
Documentation:
  Enabled: false
