require:
  - rubocop-performance
  - rubocop-rails
  - rubocop-rspec
  - rubocop-capybara
  - rubocop-factory_bot

Layout/LineLength:
  AutoCorrect: false
  Max: 120
Layout/HashAlignment:
  EnforcedHashRocketStyle: table
  EnforcedColonStyle: table

Style/StringLiterals:
  Enabled: true
  EnforcedStyle: single_quotes
Style/Documentation:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'
    - 'config/**/*'
Metrics/ClassLength:
  CountAsOne: ['array', 'hash', 'heredoc']
Metrics/MethodLength:
  CountAsOne: ['array', 'hash', 'heredoc']
  Max: 14
Metrics/ModuleLength:
  CountAsOne: ['array', 'hash', 'heredoc']

AllCops:
  NewCops: enable
  Exclude:
    - '.git/**/*'
    - '.github/**/*'
    - 'db/**/*'
    - 'config/**/*'
    - 'script/**/*'
    - 'bin/**/*'
    - 'lib/**/*'
    - 'log/**/*'
    - 'tmp/**/*'
    - 'node_modules/**/*'
    - 'vendor/**/*'

RSpec/MultipleExpectations:
  Enabled: false
RSpec/ExampleLength:
  Enabled: false
RSpec/ContextWording:
  Prefixes:
    - when
    - with
    - without
    - and
RSpec/FilePath:
  Exclude:
    - spec/requests/**/*
RSpec/NestedGroups:
  Max: 4
RSpec/BeNil:
  EnforcedStyle: be
