version: '3'
services:
  db:
    image: postgres
    volumes:
      - database_folder:/var/lib/postgresql/data
    restart: always
    networks:
      - leltar_network
  web:
    build: .
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    environment:
      - RAILS_SERVE_STATIC_FILES=true
      - RAILS_ENV=production
      - DATABASE=leltar
      - USER=postgres
      - PASSWORD=
      - HOST=db
    restart: always
    volumes:
      - public_folder:/leltar/public
    ports:
      - "3434:3000"
    networks:
      - leltar_network
    depends_on:
      - db

networks:
  leltar_network:

# Add your volumes
volumes:
  public_folder:
    external:
      name:
  database_folder:
    external:
      name:
